name: Deploy Flask App on Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip show flask  # Debugging step

    - name: Kill Previous Flask Instances
      run: |
        taskkill /IM python.exe /F || echo "No previous Flask instance running"

    - name: Run Flask Application
      run: Start-Process -FilePath "cmd.exe" -ArgumentList "/C app\start_server.bat" -NoNewWindow -Wait
